### ISSUE TITLE
Incorrect reference to SDA pin

### ISSUE THREAD

**Issue by pauljeffress** [DFRobot/DFRobot_B_LUX_V30B#1]
In two places in DFRobot_B_LUX_V30B.cpp you incorrectly reference the pins.   You use “SDA” instead of “_SDA”, so you are messing with pins referenced outside your library. So to fix that you need to change those two instances of “SDA” in your library to “_SDA”.  By the way it would be great if your library just used the common Wire.h library for low level I2C rather than bit banging the pins itself.  
Here is my working code;
void DFRobot_B_LUX_V30B::iicStopBit()
{
  digitalWrite(_SCL,HIGH);
  digitalWrite(_SDA,LOW); // **************** I changed SDA to _SDA
  delayMicroseconds(5);
  digitalWrite(_SDA,HIGH);
  delayMicroseconds(5);
  digitalWrite(_SCL,LOW);
  delayMicroseconds(5);
}

void DFRobot_B_LUX_V30B::iicSendAck(uint8_t ack)
{
  pinMode(_SDA,OUTPUT);// ****************I changed SDA to _SDA
  if(ack & 0x01 ){/*ack=0,send ACK，ack=1,send NACK*/
    digitalWrite(_SDA,HIGH);
  }else{
    digitalWrite(_SDA,LOW);
  }
  digitalWrite(_SCL,HIGH);
  delayMicroseconds(5);
  digitalWrite(_SCL,LOW);
  delayMicroseconds(5);
}

**Comment by fary99** [comment]
> In two places in DFRobot_B_LUX_V30B.cpp you incorrectly reference the pins. You use “SDA” instead of “_SDA”, so you are messing with pins referenced outside your library. So to fix that you need to change those two instances of “SDA” in your library to “_SDA”. By the way it would be great if your library just used the common Wire.h library for low level I2C rather than bit banging the pins itself.
> Here is my working code;
> void DFRobot_B_LUX_V30B::iicStopBit()
> {
> digitalWrite(_SCL,HIGH);
> digitalWrite(_SDA,LOW); // **************** I changed SDA to _SDA
> delayMicroseconds(5);
> digitalWrite(_SDA,HIGH);
> delayMicroseconds(5);
> digitalWrite(_SCL,LOW);
> delayMicroseconds(5);
> }
> 
> void DFRobot_B_LUX_V30B::iicSendAck(uint8_t ack)
> {
> pinMode(_SDA,OUTPUT);// ****************I changed SDA to _SDA
> if(ack & 0x01 ){/_ack=0,send ACK，ack=1,send NACK_/
> digitalWrite(_SDA,HIGH);
> }else{
> digitalWrite(_SDA,LOW);
> }
> digitalWrite(_SCL,HIGH);
> delayMicroseconds(5);
> digitalWrite(_SCL,LOW);
> delayMicroseconds(5);
> }

Thanks for the feedback, it has been modified
